package com.yubing.web.model.devops.config;

import java.util.Date;

public class DevopsConfigInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVOPS_CONFIG_INFO.CONFIG_ID
     *
     * @mbg.generated
     */
    private Long configId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVOPS_CONFIG_INFO.DMP_ID
     *
     * @mbg.generated
     */
    private String dmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVOPS_CONFIG_INFO.FILE_NAME
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVOPS_CONFIG_INFO.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVOPS_CONFIG_INFO.DMP_DATE
     *
     * @mbg.generated
     */
    private Date dmpDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVOPS_CONFIG_INFO.CONFIG_STATUS
     *
     * @mbg.generated
     */
    private Short configStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVOPS_CONFIG_INFO.CONFIG_CONTEXT
     *
     * @mbg.generated
     */
    private String configContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVOPS_CONFIG_INFO.CONFIG_DESCRIPTION
     *
     * @mbg.generated
     */
    private String configDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEVOPS_CONFIG_INFO.SUBMITTER
     *
     * @mbg.generated
     */
    private String submitter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVOPS_CONFIG_INFO.CONFIG_ID
     *
     * @return the value of DEVOPS_CONFIG_INFO.CONFIG_ID
     *
     * @mbg.generated
     */
    public Long getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVOPS_CONFIG_INFO.CONFIG_ID
     *
     * @param configId the value for DEVOPS_CONFIG_INFO.CONFIG_ID
     *
     * @mbg.generated
     */
    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVOPS_CONFIG_INFO.DMP_ID
     *
     * @return the value of DEVOPS_CONFIG_INFO.DMP_ID
     *
     * @mbg.generated
     */
    public String getDmpId() {
        return dmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVOPS_CONFIG_INFO.DMP_ID
     *
     * @param dmpId the value for DEVOPS_CONFIG_INFO.DMP_ID
     *
     * @mbg.generated
     */
    public void setDmpId(String dmpId) {
        this.dmpId = dmpId == null ? null : dmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVOPS_CONFIG_INFO.FILE_NAME
     *
     * @return the value of DEVOPS_CONFIG_INFO.FILE_NAME
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVOPS_CONFIG_INFO.FILE_NAME
     *
     * @param fileName the value for DEVOPS_CONFIG_INFO.FILE_NAME
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVOPS_CONFIG_INFO.CREATE_DATE
     *
     * @return the value of DEVOPS_CONFIG_INFO.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVOPS_CONFIG_INFO.CREATE_DATE
     *
     * @param createDate the value for DEVOPS_CONFIG_INFO.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVOPS_CONFIG_INFO.DMP_DATE
     *
     * @return the value of DEVOPS_CONFIG_INFO.DMP_DATE
     *
     * @mbg.generated
     */
    public Date getDmpDate() {
        return dmpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVOPS_CONFIG_INFO.DMP_DATE
     *
     * @param dmpDate the value for DEVOPS_CONFIG_INFO.DMP_DATE
     *
     * @mbg.generated
     */
    public void setDmpDate(Date dmpDate) {
        this.dmpDate = dmpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVOPS_CONFIG_INFO.CONFIG_STATUS
     *
     * @return the value of DEVOPS_CONFIG_INFO.CONFIG_STATUS
     *
     * @mbg.generated
     */
    public Short getConfigStatus() {
        return configStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVOPS_CONFIG_INFO.CONFIG_STATUS
     *
     * @param configStatus the value for DEVOPS_CONFIG_INFO.CONFIG_STATUS
     *
     * @mbg.generated
     */
    public void setConfigStatus(Short configStatus) {
        this.configStatus = configStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVOPS_CONFIG_INFO.CONFIG_CONTEXT
     *
     * @return the value of DEVOPS_CONFIG_INFO.CONFIG_CONTEXT
     *
     * @mbg.generated
     */
    public String getConfigContext() {
        return configContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVOPS_CONFIG_INFO.CONFIG_CONTEXT
     *
     * @param configContext the value for DEVOPS_CONFIG_INFO.CONFIG_CONTEXT
     *
     * @mbg.generated
     */
    public void setConfigContext(String configContext) {
        this.configContext = configContext == null ? null : configContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVOPS_CONFIG_INFO.CONFIG_DESCRIPTION
     *
     * @return the value of DEVOPS_CONFIG_INFO.CONFIG_DESCRIPTION
     *
     * @mbg.generated
     */
    public String getConfigDescription() {
        return configDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVOPS_CONFIG_INFO.CONFIG_DESCRIPTION
     *
     * @param configDescription the value for DEVOPS_CONFIG_INFO.CONFIG_DESCRIPTION
     *
     * @mbg.generated
     */
    public void setConfigDescription(String configDescription) {
        this.configDescription = configDescription == null ? null : configDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEVOPS_CONFIG_INFO.SUBMITTER
     *
     * @return the value of DEVOPS_CONFIG_INFO.SUBMITTER
     *
     * @mbg.generated
     */
    public String getSubmitter() {
        return submitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEVOPS_CONFIG_INFO.SUBMITTER
     *
     * @param submitter the value for DEVOPS_CONFIG_INFO.SUBMITTER
     *
     * @mbg.generated
     */
    public void setSubmitter(String submitter) {
        this.submitter = submitter == null ? null : submitter.trim();
    }
}