package com.yubing.web.model.devops.config;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DevopsConfigInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    public DevopsConfigInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConfigIdIsNull() {
            addCriterion("CONFIG_ID is null");
            return (Criteria) this;
        }

        public Criteria andConfigIdIsNotNull() {
            addCriterion("CONFIG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andConfigIdEqualTo(Long value) {
            addCriterion("CONFIG_ID =", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotEqualTo(Long value) {
            addCriterion("CONFIG_ID <>", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdGreaterThan(Long value) {
            addCriterion("CONFIG_ID >", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdGreaterThanOrEqualTo(Long value) {
            addCriterion("CONFIG_ID >=", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdLessThan(Long value) {
            addCriterion("CONFIG_ID <", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdLessThanOrEqualTo(Long value) {
            addCriterion("CONFIG_ID <=", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdIn(List<Long> values) {
            addCriterion("CONFIG_ID in", values, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotIn(List<Long> values) {
            addCriterion("CONFIG_ID not in", values, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdBetween(Long value1, Long value2) {
            addCriterion("CONFIG_ID between", value1, value2, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotBetween(Long value1, Long value2) {
            addCriterion("CONFIG_ID not between", value1, value2, "configId");
            return (Criteria) this;
        }

        public Criteria andDmpIdIsNull() {
            addCriterion("DMP_ID is null");
            return (Criteria) this;
        }

        public Criteria andDmpIdIsNotNull() {
            addCriterion("DMP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDmpIdEqualTo(String value) {
            addCriterion("DMP_ID =", value, "dmpId");
            return (Criteria) this;
        }

        public Criteria andDmpIdNotEqualTo(String value) {
            addCriterion("DMP_ID <>", value, "dmpId");
            return (Criteria) this;
        }

        public Criteria andDmpIdGreaterThan(String value) {
            addCriterion("DMP_ID >", value, "dmpId");
            return (Criteria) this;
        }

        public Criteria andDmpIdGreaterThanOrEqualTo(String value) {
            addCriterion("DMP_ID >=", value, "dmpId");
            return (Criteria) this;
        }

        public Criteria andDmpIdLessThan(String value) {
            addCriterion("DMP_ID <", value, "dmpId");
            return (Criteria) this;
        }

        public Criteria andDmpIdLessThanOrEqualTo(String value) {
            addCriterion("DMP_ID <=", value, "dmpId");
            return (Criteria) this;
        }

        public Criteria andDmpIdLike(String value) {
            addCriterion("DMP_ID like", value, "dmpId");
            return (Criteria) this;
        }

        public Criteria andDmpIdNotLike(String value) {
            addCriterion("DMP_ID not like", value, "dmpId");
            return (Criteria) this;
        }

        public Criteria andDmpIdIn(List<String> values) {
            addCriterion("DMP_ID in", values, "dmpId");
            return (Criteria) this;
        }

        public Criteria andDmpIdNotIn(List<String> values) {
            addCriterion("DMP_ID not in", values, "dmpId");
            return (Criteria) this;
        }

        public Criteria andDmpIdBetween(String value1, String value2) {
            addCriterion("DMP_ID between", value1, value2, "dmpId");
            return (Criteria) this;
        }

        public Criteria andDmpIdNotBetween(String value1, String value2) {
            addCriterion("DMP_ID not between", value1, value2, "dmpId");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNull() {
            addCriterion("FILE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNotNull() {
            addCriterion("FILE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFileNameEqualTo(String value) {
            addCriterion("FILE_NAME =", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotEqualTo(String value) {
            addCriterion("FILE_NAME <>", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThan(String value) {
            addCriterion("FILE_NAME >", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_NAME >=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThan(String value) {
            addCriterion("FILE_NAME <", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThanOrEqualTo(String value) {
            addCriterion("FILE_NAME <=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLike(String value) {
            addCriterion("FILE_NAME like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotLike(String value) {
            addCriterion("FILE_NAME not like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameIn(List<String> values) {
            addCriterion("FILE_NAME in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotIn(List<String> values) {
            addCriterion("FILE_NAME not in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameBetween(String value1, String value2) {
            addCriterion("FILE_NAME between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotBetween(String value1, String value2) {
            addCriterion("FILE_NAME not between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andDmpDateIsNull() {
            addCriterion("DMP_DATE is null");
            return (Criteria) this;
        }

        public Criteria andDmpDateIsNotNull() {
            addCriterion("DMP_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andDmpDateEqualTo(Date value) {
            addCriterion("DMP_DATE =", value, "dmpDate");
            return (Criteria) this;
        }

        public Criteria andDmpDateNotEqualTo(Date value) {
            addCriterion("DMP_DATE <>", value, "dmpDate");
            return (Criteria) this;
        }

        public Criteria andDmpDateGreaterThan(Date value) {
            addCriterion("DMP_DATE >", value, "dmpDate");
            return (Criteria) this;
        }

        public Criteria andDmpDateGreaterThanOrEqualTo(Date value) {
            addCriterion("DMP_DATE >=", value, "dmpDate");
            return (Criteria) this;
        }

        public Criteria andDmpDateLessThan(Date value) {
            addCriterion("DMP_DATE <", value, "dmpDate");
            return (Criteria) this;
        }

        public Criteria andDmpDateLessThanOrEqualTo(Date value) {
            addCriterion("DMP_DATE <=", value, "dmpDate");
            return (Criteria) this;
        }

        public Criteria andDmpDateIn(List<Date> values) {
            addCriterion("DMP_DATE in", values, "dmpDate");
            return (Criteria) this;
        }

        public Criteria andDmpDateNotIn(List<Date> values) {
            addCriterion("DMP_DATE not in", values, "dmpDate");
            return (Criteria) this;
        }

        public Criteria andDmpDateBetween(Date value1, Date value2) {
            addCriterion("DMP_DATE between", value1, value2, "dmpDate");
            return (Criteria) this;
        }

        public Criteria andDmpDateNotBetween(Date value1, Date value2) {
            addCriterion("DMP_DATE not between", value1, value2, "dmpDate");
            return (Criteria) this;
        }

        public Criteria andConfigStatusIsNull() {
            addCriterion("CONFIG_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andConfigStatusIsNotNull() {
            addCriterion("CONFIG_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andConfigStatusEqualTo(Short value) {
            addCriterion("CONFIG_STATUS =", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusNotEqualTo(Short value) {
            addCriterion("CONFIG_STATUS <>", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusGreaterThan(Short value) {
            addCriterion("CONFIG_STATUS >", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("CONFIG_STATUS >=", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusLessThan(Short value) {
            addCriterion("CONFIG_STATUS <", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusLessThanOrEqualTo(Short value) {
            addCriterion("CONFIG_STATUS <=", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusIn(List<Short> values) {
            addCriterion("CONFIG_STATUS in", values, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusNotIn(List<Short> values) {
            addCriterion("CONFIG_STATUS not in", values, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusBetween(Short value1, Short value2) {
            addCriterion("CONFIG_STATUS between", value1, value2, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusNotBetween(Short value1, Short value2) {
            addCriterion("CONFIG_STATUS not between", value1, value2, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigContextIsNull() {
            addCriterion("CONFIG_CONTEXT is null");
            return (Criteria) this;
        }

        public Criteria andConfigContextIsNotNull() {
            addCriterion("CONFIG_CONTEXT is not null");
            return (Criteria) this;
        }

        public Criteria andConfigContextEqualTo(String value) {
            addCriterion("CONFIG_CONTEXT =", value, "configContext");
            return (Criteria) this;
        }

        public Criteria andConfigContextNotEqualTo(String value) {
            addCriterion("CONFIG_CONTEXT <>", value, "configContext");
            return (Criteria) this;
        }

        public Criteria andConfigContextGreaterThan(String value) {
            addCriterion("CONFIG_CONTEXT >", value, "configContext");
            return (Criteria) this;
        }

        public Criteria andConfigContextGreaterThanOrEqualTo(String value) {
            addCriterion("CONFIG_CONTEXT >=", value, "configContext");
            return (Criteria) this;
        }

        public Criteria andConfigContextLessThan(String value) {
            addCriterion("CONFIG_CONTEXT <", value, "configContext");
            return (Criteria) this;
        }

        public Criteria andConfigContextLessThanOrEqualTo(String value) {
            addCriterion("CONFIG_CONTEXT <=", value, "configContext");
            return (Criteria) this;
        }

        public Criteria andConfigContextLike(String value) {
            addCriterion("CONFIG_CONTEXT like", value, "configContext");
            return (Criteria) this;
        }

        public Criteria andConfigContextNotLike(String value) {
            addCriterion("CONFIG_CONTEXT not like", value, "configContext");
            return (Criteria) this;
        }

        public Criteria andConfigContextIn(List<String> values) {
            addCriterion("CONFIG_CONTEXT in", values, "configContext");
            return (Criteria) this;
        }

        public Criteria andConfigContextNotIn(List<String> values) {
            addCriterion("CONFIG_CONTEXT not in", values, "configContext");
            return (Criteria) this;
        }

        public Criteria andConfigContextBetween(String value1, String value2) {
            addCriterion("CONFIG_CONTEXT between", value1, value2, "configContext");
            return (Criteria) this;
        }

        public Criteria andConfigContextNotBetween(String value1, String value2) {
            addCriterion("CONFIG_CONTEXT not between", value1, value2, "configContext");
            return (Criteria) this;
        }

        public Criteria andConfigDescriptionIsNull() {
            addCriterion("CONFIG_DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andConfigDescriptionIsNotNull() {
            addCriterion("CONFIG_DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andConfigDescriptionEqualTo(String value) {
            addCriterion("CONFIG_DESCRIPTION =", value, "configDescription");
            return (Criteria) this;
        }

        public Criteria andConfigDescriptionNotEqualTo(String value) {
            addCriterion("CONFIG_DESCRIPTION <>", value, "configDescription");
            return (Criteria) this;
        }

        public Criteria andConfigDescriptionGreaterThan(String value) {
            addCriterion("CONFIG_DESCRIPTION >", value, "configDescription");
            return (Criteria) this;
        }

        public Criteria andConfigDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("CONFIG_DESCRIPTION >=", value, "configDescription");
            return (Criteria) this;
        }

        public Criteria andConfigDescriptionLessThan(String value) {
            addCriterion("CONFIG_DESCRIPTION <", value, "configDescription");
            return (Criteria) this;
        }

        public Criteria andConfigDescriptionLessThanOrEqualTo(String value) {
            addCriterion("CONFIG_DESCRIPTION <=", value, "configDescription");
            return (Criteria) this;
        }

        public Criteria andConfigDescriptionLike(String value) {
            addCriterion("CONFIG_DESCRIPTION like", value, "configDescription");
            return (Criteria) this;
        }

        public Criteria andConfigDescriptionNotLike(String value) {
            addCriterion("CONFIG_DESCRIPTION not like", value, "configDescription");
            return (Criteria) this;
        }

        public Criteria andConfigDescriptionIn(List<String> values) {
            addCriterion("CONFIG_DESCRIPTION in", values, "configDescription");
            return (Criteria) this;
        }

        public Criteria andConfigDescriptionNotIn(List<String> values) {
            addCriterion("CONFIG_DESCRIPTION not in", values, "configDescription");
            return (Criteria) this;
        }

        public Criteria andConfigDescriptionBetween(String value1, String value2) {
            addCriterion("CONFIG_DESCRIPTION between", value1, value2, "configDescription");
            return (Criteria) this;
        }

        public Criteria andConfigDescriptionNotBetween(String value1, String value2) {
            addCriterion("CONFIG_DESCRIPTION not between", value1, value2, "configDescription");
            return (Criteria) this;
        }

        public Criteria andSubmitterIsNull() {
            addCriterion("SUBMITTER is null");
            return (Criteria) this;
        }

        public Criteria andSubmitterIsNotNull() {
            addCriterion("SUBMITTER is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitterEqualTo(String value) {
            addCriterion("SUBMITTER =", value, "submitter");
            return (Criteria) this;
        }

        public Criteria andSubmitterNotEqualTo(String value) {
            addCriterion("SUBMITTER <>", value, "submitter");
            return (Criteria) this;
        }

        public Criteria andSubmitterGreaterThan(String value) {
            addCriterion("SUBMITTER >", value, "submitter");
            return (Criteria) this;
        }

        public Criteria andSubmitterGreaterThanOrEqualTo(String value) {
            addCriterion("SUBMITTER >=", value, "submitter");
            return (Criteria) this;
        }

        public Criteria andSubmitterLessThan(String value) {
            addCriterion("SUBMITTER <", value, "submitter");
            return (Criteria) this;
        }

        public Criteria andSubmitterLessThanOrEqualTo(String value) {
            addCriterion("SUBMITTER <=", value, "submitter");
            return (Criteria) this;
        }

        public Criteria andSubmitterLike(String value) {
            addCriterion("SUBMITTER like", value, "submitter");
            return (Criteria) this;
        }

        public Criteria andSubmitterNotLike(String value) {
            addCriterion("SUBMITTER not like", value, "submitter");
            return (Criteria) this;
        }

        public Criteria andSubmitterIn(List<String> values) {
            addCriterion("SUBMITTER in", values, "submitter");
            return (Criteria) this;
        }

        public Criteria andSubmitterNotIn(List<String> values) {
            addCriterion("SUBMITTER not in", values, "submitter");
            return (Criteria) this;
        }

        public Criteria andSubmitterBetween(String value1, String value2) {
            addCriterion("SUBMITTER between", value1, value2, "submitter");
            return (Criteria) this;
        }

        public Criteria andSubmitterNotBetween(String value1, String value2) {
            addCriterion("SUBMITTER not between", value1, value2, "submitter");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}