package com.yubing.web.mapper.devops.config;

import com.yubing.web.model.devops.config.DevopsConfigInfo;
import com.yubing.web.model.devops.config.DevopsConfigInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DevopsConfigInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    long countByExample(DevopsConfigInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    int deleteByExample(DevopsConfigInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    int insert(DevopsConfigInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    int insertSelective(DevopsConfigInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    List<DevopsConfigInfo> selectByExample(DevopsConfigInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    DevopsConfigInfo selectByPrimaryKey(Long configId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DevopsConfigInfo record, @Param("example") DevopsConfigInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DevopsConfigInfo record, @Param("example") DevopsConfigInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DevopsConfigInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEVOPS_CONFIG_INFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DevopsConfigInfo record);
}